Repository fossology/FOSSologyUI, pull requests merged in 2021-07, with the labels that each got.

#52 feat(folder): add edit folder page
  src/Routes.js
  src/api/folders.js
  src/constants/endpoints.js
  src/pages/Organize/Folder/Edit/index.js
  src/services/folders.js
Labels: needs review, needs test

#51 fix(search): add error check and fix duplicate ids
  src/components/Widgets/Input/index.js
  src/pages/Search/index.js
Labels: ready

#53 feat(browse): Added the prototype for the uploads page
  src/api/browse.js
  src/api/sendRequest.js
  src/components/Widgets/Input/index.js
  src/constants/endpoints.js
  src/pages/Browse/index.js
  src/pages/Search/index.js
  src/services/browse.js
  src/styles/global.css
Labels: ready

#54 feat(folder): add move upload or folder
  src/Routes.js
  src/api/folders.js
  src/constants/endpoints.js
  src/pages/Organize/Folder/Create/index.js
  src/pages/Organize/Folder/Delete/index.js
  src/pages/Organize/Folder/Edit/index.js
  src/pages/Organize/Folder/Move/index.js
  src/services/folders.js
Labels: ready

#57 fix(routes): added the routes for all pages
  src/Routes.js
  src/pages/Jobs/AllJobs/index.js
  src/pages/Jobs/MyRecentJobs/index.js
  src/pages/Jobs/ScheduleAgents/index.js
  src/pages/Organize/Folder/Create/index.js
  src/pages/Organize/Folder/Delete/index.js
  src/pages/Organize/Folder/Edit/index.js
  src/pages/Organize/Folder/Move/index.js
  src/pages/Organize/License/index.js
  src/pages/Organize/Uploads/Edit/index.js
  src/pages/Organize/Uploads/Move/index.js
  src/pages/Upload/File/index.js
  src/pages/Upload/ImportReport/index.js
  src/pages/Upload/Server/index.js
  src/pages/Upload/Url/index.js
  src/pages/Upload/Vcs/index.js
Labels: needs review, needs test

#65 fix(ui): fixed the bugs in search, overview, create folder page
  src/pages/Help/Overview/index.js
  src/pages/Organize/Folder/Move/index.js
  src/pages/Search/index.js
Labels: needs review, needs test

#66 fix(UI): open link in new tab and fix heading
  src/constants/externalLinks.js
  src/pages/Help/Overview/index.js
Labels: needs review, needs test

#70 feat(one-shot): Added the analysis, monk and copyright page
  src/Routes.js
  src/components/Header/index.js
  src/constants/routes.js
  src/pages/Upload/OneShotAnalysis/index.js
  src/pages/Upload/OneShotCopyright/index.js
  src/pages/Upload/OneShotMonk/index.js
Labels: needs review, needs test

#82 fix(auth): logout user when token is revoked
  src/api/sendRequest.js
Labels: needs review, needs test

#74 fix(api): remove the redundancy of credentials
  src/api/auth.js
  src/api/browse.js
  src/api/folders.js
  src/api/getFolder.js
  src/api/jobs.js
  src/api/search.js
  src/api/sendRequest.js
  src/api/upload.js
  src/api/users.js
Labels: needs review, needs test

#55 feat(folder): add unlink upload or folder
  src/Routes.js
  src/pages/Organize/Folder/Unlink/index.js
Labels: ready

#62 feat(moveUpload): Added the move upload or copy upload page
  src/api/organizeUploads.js
  src/components/Widgets/Input/index.js
  src/constants/endpoints.js
  src/pages/Organize/Uploads/Move/index.js
  src/services/organizeUploads.js
Labels: ready

#75 fix(service): remove duplicate api functions
  src/api/getFolder.js
  src/pages/Organize/Uploads/Delete/index.js
  src/pages/Upload/File/index.js
  src/services/getFolder.js
Labels: ready

#73 feat(group): add create group page
  src/Routes.js
  src/api/groups.js
  src/components/Header/index.js
  src/constants/endpoints.js
  src/constants/routes.js
  src/pages/Admin/Group/Create/index.jsx
  src/pages/Organize/Uploads/Move/index.js
  src/services/groups.js
  src/shared/authHelper.js
Labels: ready

#76 feat(user): add delete user page
  src/Routes.js
  src/api/users.js
  src/components/Header/index.js
  src/constants/endpoints.js
  src/constants/routes.js
  src/pages/Admin/Users/Delete/index.jsx
  src/services/users.js
  src/shared/authHelper.js
Labels: ready

#77 feat(edit-upload): added the edit upload page
  src/api/organizeUploads.js
  src/pages/Organize/Uploads/Edit/index.js
  src/services/organizeUploads.js
Labels: ready

#79 feat(jobs): add schedule analysis page
  src/api/browse.js
  src/components/Upload/CommonFields/OptionalAnalysis/index.js
  src/components/Upload/CommonFields/index.js
  src/constants/endpoints.js
  src/pages/Jobs/ScheduleAgents/index.js
Labels: needs review, needs test

#92 fix(agents): use agent preference from local storage
  src/pages/Jobs/ScheduleAgents/index.js
  src/pages/Upload/File/index.js
  src/shared/storageHelper.js
Labels: needs test

#69 feat(Infra): Introduced Config file for enviornment variables
  .env.sample
  .eslintrc.json
  Dockerfile
  README.md
  src/constants/endpoints.js
Labels: needs review, needs test

#86 fix(header): fix header on small screen size
  src/__snapshots__/App.test.js.snap
  src/components/Header/index.js
  src/styles/global.css
Labels: needs review

#60 feat(folder-navigation): add folder tree view
  package.json
  src/App.js
  src/components/TreeContainer/index.css
  src/components/TreeContainer/index.js
  src/pages/Browse/index.js
  yarn.lock
Labels: ready

#71 feat(vcs): added the upload vcs page
  src/api/sendRequest.js
  src/api/upload.js
  src/constants/endpoints.js
  src/pages/Upload/Vcs/index.js
  src/services/upload.js
Labels: needs review, needs test

#94 feat(ci): Mark PRs with conflicts
  .github/workflows/conflict-check.yml
Labels: needs review

#80 feat(storybook): add storybook initial setup
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/stories/Button.jsx
  src/stories/Button.stories.jsx
  src/stories/Header.jsx
  src/stories/Header.stories.jsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.jsx
  src/stories/Page.stories.jsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  yarn.lock
Labels: needs review, needs test

#106 feat(env): added the auth variables in env
  .env.sample
  src/constants/auth.js
Labels: ready

#110 fix(errors): fixed the invalid errors
  src/api/sendRequest.js
Labels: needs review, needs test

#112 fix(schedule-jobs): fix the upload list on schedule jobs page
  src/pages/Jobs/ScheduleAgents/index.jsx
Labels: needs review, needs test

#61 feat(scripts): Added the script for copyrights csv
  package.json
  scripts/copyrights.csv
  scripts/copyrights.js
  scripts/copyrightsScript.js
  yarn.lock
Labels: ready

#102 fix(gh-pages): added the public url
  .github/workflows/deploy.yml
  src/Routes.js
Labels: needs test

#107 fix(query-params): sanitize url query parameters
  src/api/licenses.js
  src/api/organizeUploads.js
  src/constants/endpoints.js
Labels: ready

#113 fix(links): keep external links in externalLinks.js file
  src/components/Header/index.jsx
  src/constants/externalLinks.js
  src/constants/routes.js
  src/pages/Help/About/index.jsx
Labels: ready

#116 fix(imports): Update absolute import to relative in layout component
  src/shared/AdminLayout.jsx
  src/shared/PrivateLayout.jsx
  src/shared/PublicLayout.jsx
Labels: needs test

#104 feat(user-group): display user group in dropdown
  src/api/auth.js
  src/api/browse.js
  src/api/groups.js
  src/api/licenses.js
  src/api/organizeUploads.js
  src/api/search.js
  src/api/sendRequest.js
  src/api/upload.js
  src/api/users.js
  src/components/Header/index.jsx
  src/components/Widgets/TextIcon/index.jsx
  src/pages/Browse/index.jsx
  src/pages/Home/index.jsx
  src/pages/Jobs/ScheduleAgents/index.jsx
  src/pages/Organize/License/index.jsx
  src/pages/Organize/Uploads/Delete/index.jsx
  src/pages/Organize/Uploads/Edit/index.jsx
  src/pages/Organize/Uploads/Move/index.jsx
  src/pages/Search/index.jsx
  src/pages/Upload/Vcs/index.jsx
  src/services/groups.js
  src/services/organizeUploads.js
  src/shared/AdminLayout.jsx
  src/shared/authHelper.js
  src/shared/helper.js
Labels: needs test

#115 fix(vcs): fixed the upload vcs page
  src/api/sendRequest.js
  src/pages/Admin/License/Create/index.jsx
  src/pages/Upload/File/index.jsx
  src/pages/Upload/Vcs/index.jsx
Labels: needs review, needs test

#114 feat(active-navbar): added the active class to nav items
  .eslintrc.json
  src/__snapshots__/App.test.jsx.snap
  src/api/groups.js
  src/components/Header/index.jsx
  src/styles/globalStyle.js
  src/styles/theme.js
Labels: has merge conflicts, ready

#119 fix(api): sanitize the names of api functions
  src/api/browse.js
  src/api/search.js
  src/api/upload.js
  src/pages/Jobs/ScheduleAgents/index.jsx
  src/pages/Organize/Uploads/Edit/index.jsx
  src/pages/Upload/File/index.jsx
  src/pages/Upload/Vcs/index.jsx
  src/services/browse.js
  src/services/search.js
  src/services/upload.js
Labels: has merge conflicts, ready

#120 feat(license): added the candidate new license page
  src/Routes.jsx
  src/api/browse.js
  src/api/licenses.js
  src/api/search.js
  src/components/Header/index.jsx
  src/constants/endpoints.js
  src/constants/routes.js
  src/pages/Organize/License/CandidateLicense/index.jsx
  src/pages/Organize/License/Create/index.jsx
  src/services/licenses.js
Labels: has merge conflicts, needs test

#121 feat(upload-server): added the upload server page
  src/pages/Upload/Server/index.jsx
Labels: needs review, needs test

#122 refactor(handleError): add reusable function for error handling
  scripts/copyrightsScript.js
  src/pages/Admin/Users/Delete/index.jsx
  src/pages/Organize/Folder/Create/index.jsx
  src/pages/Organize/Folder/Delete/index.jsx
  src/pages/Organize/Folder/Edit/index.jsx
  src/pages/Organize/Folder/Move/index.jsx
  src/pages/Organize/Folder/Unlink/index.jsx
  src/pages/Organize/Uploads/Edit/index.jsx
  src/pages/Organize/Uploads/Move/index.jsx
  src/pages/Upload/File/index.jsx
  src/pages/Upload/Vcs/index.jsx
  src/services/browse.js
  src/shared/authHelper.js
  src/shared/helper.js
Labels: needs review, needs test

#127 fix(vcs): fixed the analysis of scanData
  src/pages/Upload/Vcs/index.jsx
Labels: needs review, needs test

#129 fix(react-helmet): use react-helmet-async to fix console error
  package.json
  src/App.test.jsx
  src/__snapshots__/App.test.jsx.snap
  src/components/Title/index.jsx
  src/index.jsx
  yarn.lock
Labels: needs review, needs test

#126 fix(errors): Added the error checks in deleteUploads
  src/pages/Organize/Uploads/Delete/index.jsx
Labels: needs review, needs test

#124 feat(alert): alert message on homepage for logout error
  src/api/sendRequest.js
  src/components/Header/index.jsx
  src/pages/Home/index.jsx
  src/shared/authHelper.js
Labels: needs test

#132 fix(ux): fixed the ux of upload pages
  src/pages/Upload/File/index.jsx
  src/pages/Upload/Server/index.jsx
  src/pages/Upload/Vcs/index.jsx
  src/shared/helper.js
Labels: ready
