Repository fossology/FOSSologyUI, pull requests merged in 2021-06, with the labels that each got.

#23 feat(about): added the About page
  src/Routes.js
  src/components/Footer/index.js
  src/components/Header/index.js
  src/constants/routes.js
  src/data/copyright.js
  src/pages/Help/About/index.js
  src/styles/globalStyle.js
Labels: needs review, needs test

#32 fix(ui): replaced entities and updated the navbar
  src/components/Header/index.js
  src/pages/Help/Overview/index.js
Labels: needs test

#37 feat(CI/CD): add github actions for CI/CD test
  .github/workflows/test.yml
  src/App.test.js
  src/__snapshots__/App.test.js.snap
Labels: needs review, needs test

#31 feat(thirdPartyLicense): add third party licenses
  public/thirdPartyLicenses.html
  src/Routes.js
  src/components/Header/index.js
  src/constants/routes.js
  src/pages/Help/ThirdPartyLicenses/index.css
  src/pages/Help/ThirdPartyLicenses/index.js
Labels: needs test

#36 feat(ui): fixed the dropdown styles and added the sub-dropdown
  src/components/Header/index.js
  src/constants/routes.js
  src/pages/Organize/Folder/Create/index.js
  src/pages/Organize/Folder/Delete/index.js
  src/pages/Organize/Folder/Edit/index.js
  src/pages/Organize/Folder/Move/index.js
  src/pages/Organize/Uploads/Delete/index.js
  src/pages/Organize/Uploads/Edit/index.js
  src/pages/Organize/Uploads/Move/index.js
  src/styles/globalStyle.js
Labels: ready

#39 feat(importReport): added the report import page of uploads
  src/Routes.js
  src/components/Widgets/Input/index.js
  src/pages/Upload/ImportReport/index.js
Labels: ready

#38 feat(theme): added the custom theme functionality in the navbar
  src/App.js
  src/components/Header/index.js
  src/context/index.js
  src/shared/storageHelper.js
  src/styles/globalStyle.js
  src/styles/theme.js
Labels: ready

#35 fix(404): redirect to home page if page not found
  LICENSES/IndieFlower-OFL.txt
  src/Routes.js
  src/assets/fonts/IndieFlower-Regular.license
  src/assets/fonts/IndieFlower-Regular.ttf
  src/pages/ErrorPage/index.js
  src/styles/global.css
Labels: ready

#34 feat(search): added the search page
  src/Routes.js
  src/api/search.js
  src/constants/endpoints.js
  src/pages/Search/index.js
  src/services/search.js
  src/shared/helper.js
Labels: needs review, needs test

#47 feat(ui): added the custom component for alert and tooltip
  src/components/Widgets/Alert/index.js
  src/components/Widgets/Tooltip/index.js
  src/pages/Home/index.js
Labels: needs test

#45 feat(folder): add create folder page
  src/Routes.js
  src/api/folders.js
  src/pages/Organize/Folder/Create/index.js
  src/pages/Organize/Folder/Delete/index.js
  src/services/folders.js
Labels: needs review, needs test
