Repository fossology/FOSSologyUI, pull requests merged in 2021-08, with the labels that each got.

#128 feat(reuse): add all reuse options and update corresponding api
  src/api/folders.js
  src/api/organizeUploads.js
  src/api/upload.js
  src/components/Upload/CommonFields/UploadReuse/index.jsx
  src/components/Upload/CommonFields/index.jsx
  src/components/Widgets/Input/index.jsx
  src/constants/endpoints.js
  src/pages/Jobs/ScheduleAgents/index.jsx
  src/pages/Upload/File/index.jsx
  src/pages/Upload/Server/index.jsx
  src/pages/Upload/Vcs/index.jsx
  src/services/folders.js
  src/services/organizeUploads.js
Labels: needs review, needs test

#133 fix(uplods-move-copy): added the fallback condition
  src/pages/Organize/Uploads/Move/index.jsx
Labels: needs review, needs test

#135 feat(API): migrate API from v1 to v2
  .env.sample
  .github/workflows/deploy.yml
  README.md
Labels: needs review, needs test

#136 feat(browse): added the browsing of uploads with folders
  src/components/TreeContainer/index.css
  src/components/TreeContainer/index.jsx
  src/pages/Browse/index.jsx
Labels: needs review, needs test

#125 feat(url): added the upload from url page
  src/api/upload.js
  src/components/Upload/CommonFields/AccessLevel/index.jsx
  src/components/Upload/CommonFields/IgnoreScm/index.jsx
  src/components/Upload/CommonFields/LicenseDecider/index.jsx
  src/components/Upload/CommonFields/OptionalAnalysis/index.jsx
  src/pages/Upload/Server/index.jsx
  src/pages/Upload/Url/index.jsx
  src/pages/Upload/Vcs/index.jsx
  src/services/upload.js
Labels: ready

#137 feat(search): added the pagination in search page
  src/api/search.js
  src/pages/Search/index.jsx
  src/services/search.js
Labels: needs test

#138 feat(group): use default group returned from API
  src/api/sendRequest.js
  src/components/Header/index.jsx
  src/pages/Jobs/ScheduleAgents/index.jsx
  src/pages/Upload/File/index.jsx
  src/pages/Upload/Server/index.jsx
  src/pages/Upload/Vcs/index.jsx
Labels: needs review, needs test

#140 fix(nameInitials): add null check in name initials function
  src/shared/helper.js
Labels: needs review, needs test

#142 fix(highlight-group): highlight the current selected group
  src/components/Header/index.jsx
  src/services/users.js
  src/styles/globalStyle.js
Labels: needs review, needs test

#143 fix(login-form): add border to form in dark theme
  src/__snapshots__/App.test.jsx.snap
  src/pages/Home/style.js
Labels: needs review, needs test

#144 fix(ui): fixed the snackbar now ui not shifting
  src/components/Widgets/Alert/index.jsx
  src/pages/Admin/Group/Create/index.jsx
  src/pages/Admin/Users/Delete/index.jsx
  src/pages/Browse/index.jsx
  src/pages/Home/index.jsx
  src/pages/Jobs/ScheduleAgents/index.jsx
  src/pages/Organize/Folder/Create/index.jsx
  src/pages/Organize/Folder/Delete/index.jsx
  src/pages/Organize/Folder/Edit/index.jsx
  src/pages/Organize/Folder/Move/index.jsx
  src/pages/Organize/Folder/Unlink/index.jsx
  src/pages/Organize/License/CandidateLicense/index.jsx
  src/pages/Organize/License/Create/index.jsx
  src/pages/Organize/Uploads/Delete/index.jsx
  src/pages/Organize/Uploads/Edit/index.jsx
  src/pages/Organize/Uploads/Move/index.jsx
  src/pages/Search/index.jsx
  src/pages/Upload/File/index.jsx
  src/pages/Upload/Server/index.jsx
  src/pages/Upload/Url/index.jsx
  src/pages/Upload/Vcs/index.jsx
  src/styles/global.css
Labels: needs review, needs test

#145 fix(jobs): fixed the jobs api of scheduleAnalysis
  src/api/jobs.js
  src/api/upload.js
  src/constants/endpoints.js
  src/pages/Jobs/ScheduleAgents/index.jsx
  src/pages/Upload/File/index.jsx
  src/pages/Upload/Url/index.jsx
  src/pages/Upload/Vcs/index.jsx
  src/services/jobs.js
  src/services/upload.js
Labels: needs test

#151 fix(footer): fixed the footer alignment
  src/__snapshots__/App.test.jsx.snap
  src/components/Footer/index.jsx
Labels: needs review, needs test

#141 feat(fossology-version): use fossology version from info API
  src/Routes.jsx
  src/__snapshots__/App.test.jsx.snap
  src/api/info.js
  src/components/Footer/index.jsx
  src/constants/endpoints.js
  src/services/info.js
  src/shared/AdminLayout.jsx
  src/shared/PrivateLayout.jsx
  src/shared/PublicLayout.jsx
  src/shared/storageHelper.js
Labels: needs test

#150 feat(report): add export report option on browse page
  .eslintrc.json
  src/api/jobs.js
  src/api/sendRequest.js
  src/components/Widgets/Input/index.jsx
  src/constants/endpoints.js
  src/pages/Browse/index.jsx
  src/services/jobs.js
  src/shared/helper.js
Labels: needs review, needs test
