Repository fossology/FOSSologyUI, pull requests merged in 2022-05, with the labels that each got.

#205 fix(ui): light and dark mode refresh bug fixed
  src/App.jsx
  src/context/index.jsx
Labels: needs review, needs test

#196 feat(delete user): Disabled deletion of default users
  src/pages/Admin/Users/Delete/index.jsx
Labels: needs test

#206 chore(deps): Updated dependencies
  .github/workflows/test.yml
  package.json
  src/pages/Home/__snapshots__/index.test.jsx.snap
  yarn.lock
Labels: ready
