Repository fossology/FOSSologyUI, pull requests merged in 2022-08, with the labels that each got.

#229 feature(ui): ui and formdata implementation for the `add user` page
  src/Routes.jsx
  src/api/users.js
  src/components/Header/index.jsx
  src/components/Upload/CommonFields/AccessLevel/index.jsx
  src/components/Upload/CommonFields/index.jsx
  src/constants/constants.js
  src/constants/endpoints.js
  src/constants/messages.js
  src/constants/routes.js
  src/pages/Admin/Users/Add/index.jsx
  src/services/users.js
Labels: needs test

#245 feat(ui): All jobs only accessible by admin
  src/api/jobs.js
  src/components/Header/index.jsx
  src/constants/endpoints.js
  src/pages/Jobs/AllJobs/index.jsx
  src/pages/Jobs/MyRecentJobs/index.jsx
  src/services/jobs.js
Labels: needs test

#246 fix(licenses): header fixed and limit for responses removed
  src/pages/BrowseUploads/LicenseBrowser/index.jsx
Labels: needs review, needs test

#241 feat(ui): added delete group page
  .gitignore
  package.json
  src/App.jsx
  src/Routes.jsx
  src/api/groups.js
  src/components/Modals/DeleteConfirmation/index.jsx
  src/components/Widgets/Button/index.jsx
  src/constants/endpoints.js
  src/constants/messages.js
  src/pages/Admin/Group/Delete/index.jsx
  src/services/groups.js
  yarn.lock
Labels: enhancement, needs test

#236 feature(ui): ui and styling for the `edit user page`
  src/Routes.jsx
  src/api/auth.js
  src/api/users.js
  src/components/Header/index.jsx
  src/components/Upload/CommonFields/AccessLevel/index.jsx
  src/components/Widgets/Input/index.jsx
  src/components/Widgets/Modal/index.css
  src/components/Widgets/Modal/index.jsx
  src/constants/constants.js
  src/constants/endpoints.js
  src/constants/routes.js
  src/pages/Admin/Users/Edit/index.css
  src/pages/Admin/Users/Edit/index.jsx
  src/pages/Admin/Users/Edit/token_space.jsx
  src/services/users.js
  src/utils/index.js
Labels: ready
