Repository fossology/FOSSologyUI, pull requests merged in 2022-06, with the labels that each got.

#211 fix(update): Exported constants from the search component
  src/constants/constants.js
  src/pages/Search/index.jsx
Labels: ready

#209 refactor(api): removed credentials from api request module
  src/api/sendRequest.js
  src/api/sendRequest.test.js
  src/api/upload.js
  src/api/upload.test.js
  src/api/users.js
  src/api/users.test.js
Labels: ready

#217 fix(dependencies): fix vulnerabilities
  .github/workflows/test.yml
  .gitignore
  .yarn/releases/yarn-3.2.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: needs review

#219 Exported constants from upload directory and reused them
  src/constants/constants.js
  src/pages/Search/index.jsx
  src/pages/Upload/File/index.jsx
  src/pages/Upload/ImportReport/index.jsx
  src/pages/Upload/Server/index.jsx
  src/pages/Upload/Url/index.jsx
  src/pages/Upload/Vcs/index.jsx
Labels: ready

#187 fix (components/widgets/input): Warning while loading delete user page
  src/components/Widgets/Input/index.jsx
Labels: ready

#230 fix(browse): search bar function implemented
  src/pages/Browse/index.jsx
Labels: ready

#232 feat(ui): implementation of mantainance page on the admin section
  src/Routes.jsx
  src/components/Header/index.jsx
  src/constants/constants.js
  src/constants/routes.js
  src/pages/Admin/Mantainance/index.jsx
Labels: ready

#223 feature(ui): `/allRecentJobs` page completed
  src/api/jobs.js
  src/pages/Jobs/AllJobs/index.jsx
  src/services/jobs.js
Labels: needs review, needs test
